version: '3.8'

services:
  recyclo-postgres:
    image: postgres
    container_name: recyclo-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: recyclo-backend
    depends_on:
      - recyclo-postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
